# Generated by Django 4.2.5 on 2024-01-27 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blogtable_blgcmt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtable',
            name='blgcmt',
        ),
    ]
