# Generated by Django 4.2.5 on 2024-01-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_remove_blogtable_blgcmt'),
    ]

    operations = [
        migrations.CreateModel(
            name='commenttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=32)),
                ('comment_time', models.DateTimeField()),
                ('is_delete', models.BooleanField(default=False)),
                ('comment_by', models.CharField(max_length=100)),
                ('cmt', models.CharField(max_length=1000)),
            ],
        ),
    ]
