# Generated by Django 4.2.5 on 2024-01-27 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_commenttable'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commenttable',
            table='commenttable',
        ),
    ]
